name: 'Docker action to say hello'
description: 'Say hello world to user'
inputs:
  who-to-great:
    description: 'Who to great?'
    required: true
    default: "world"
outputs:
  time: 
    description: "The time we said hello"
runs:
  using: 'docker'
  image: 'DockerFile'
  args:
    - ${{ inputs.who-to-great }}

