name: GitHub Actions Demo

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-18.04
   steps:
   - uses: actions/checkout@v1
   - name: List env
     run: |
       env
       ls -ls
   - name: Dump runner context
     run: echo '${{ toJSON(runner) }}'
   - name: Dump github context
     run: echo '${{ toJSON(github) }}'
 
