name: GitHub Actions Demo

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "15 6 * * 7"
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v1
   - name: List env
     run: |
       env
       ls -la
  
